### ISSUE TITLE
Allow user to set and save daily consumption limit in SUB

### ISSUE THREAD

**Issue by SUB-BJ** [SubstratumNetwork/SubstratumNode#102]
As a SubNode user I can set a daily consumption threshold in SUB so that I can manage how much I consume by how much I spend.

Acceptance Criteria

Input field with example beside input or using the replace text 125.100 SUB

By default this is empty or “no limit”

CLI shows console messages for notifications
_[Dan comments: I think this will turn out to be unworkable. A future docker- or git-like command-line client could do this, but the command-line Node we have now struggles to accept passwords and such from the console, and that's even in special non-serving modes.]_

GUI shows modal alert message

Warning notification at 75% usage - “You’ve used 75% of your daily consumption limit.”

Warning notification at 90% usage - “You’ve used 90% of your daily consumption limit. Consuming will be automatically prevented by SubstratumNode.”

Consumption prevention notification at 100% - “You’ve used 100% of your daily consumption limit. SubstratumNode will automatically prevent consuming until the end of the limit timeframe reset.”
_[Dan comments: A non-negotiable hard limit could be quite a bad UX. Perhaps we could start requiring special permission at 100%? Obstinate, unrelenting refusal is the sort of thing one would expect when the consuming wallet is _empty._]_

Daily means every 24 hrs and resets at 0000 hrs

**Comment by substratumservices** [comment]
A tentative mostly-one-person design for this feature would produce the following cards. Before these cards are formally created, it may be a good idea to have a more in-depth design meeting to discover problems with this design.

1. Estimated Wallet Balance - Keep an estimated wallet balance in the Node at least for the consuming wallet, and for the earning wallet too if it's just as easy. Perhaps this would be best implemented by a balance field inside the Wallet type, perhaps by some other mechanism. It should be updated absolutely whenever the BlockchainBridge discovers the current balance for the wallet from the blockchain, and relatively (at least for the consuming wallet) whenever the Accountant adds a Payable amount. It may be necessary to keep two values: a last-known-balance-from-the-blockchain as well as debits-the-blockchain-doesn't-know-about-yet.

1. Balance Snapshot - Add the capability for the database to hold at least one timestamped balance snapshot for at least the consuming wallet. On the occasion of startup, and also as it does its regular cyclic chores, the Accountant should check to see whether the latest snapshot is 24 hours old yet. If it is, another snapshot should be taken and stored.

1. GUI Notification - Add the capability for the Node to generate a notification to all its UIs through the UI Gateway, containing plain text or possibly HTML. (Consider the implications of eventual internationalization; don't choose a design that makes it more difficult than necessary.) Add code to the GUI that will display the notification to the user, along with a single dismissal button. Consider a mechanism to disable the display of multiple simultaneous notifications of the same type that all have to be dismissed individually.

1. GUI Request for Comment - Add the capability for the Node to generate a question for all its UIs to ask the user. When the user answers the question from one UI, the other UIs should be instructed to stop presenting the question. The first answer type should be a pair of buttons: Yes/No, Apply/Cancel, etc. (Once again, consider the implications of eventual internationalization.) The code in the Node that asks the question should also make provision for processing the answer when it arrives, perhaps in the form of a Future or an actor message.

1. Queue Client Requests - Add the capability to begin queueing client requests (probably in the Proxy Server instead of relaying them to the Hopper) while a question is presented to the user via the UI Gateway, and then based on the answer, either send out everything that has accumulated in the queue, or abandon all the requests and close their streams. (Perhaps the first version of this could hardcode a particular URL: "__Really__ visit ilovecats.com?")

1. Daily Consumption Limit - Add a possibly-NULL daily consumption limit to the CONFIG table. If the consumption limit is populated, any request whose cost, subtracted from the current estimated consuming-wallet balance, would drive the difference between that and the most-current balance snapshot above the daily consumption limit should begin queueing requests and trigger a question to the user via the UI: "This will exceed your daily consumption limit. Continue?" If there is a daily consumption limit but no connected UI, decide whether the Node should start dropping all client requests, or whether it should ignore the limit and accept them. On the other hand, if there is a UI, and a pending "Continue?" question is displayed, and a queue of requests is waiting, and a new balance snapshot appears, the question should be taken down and whatever portion of the request queue does not violate the new consumption limit should be sent off.

1. Threshold Warnings - Add code to send notifications to the UIs when the 75% and 90% thresholds on the daily consumption limit are passed.

1. Daily Consumption Limit Setting - Add UX to the GUI allowing a daily consumption limit to be modified or eliminated. (Populate it initially via --dump-config.) When it's set, send it to the UI Gateway and have the Node store it in the database.
