### ISSUE TITLE
How to enter multiple neighbors in the GUI

### ISSUE THREAD

**Issue by meizenga** [SubstratumNetwork/SubstratumNode#25]
**SubstratumNode Version**
commit f5d67ec 

**Describe the bug**
The CLI accepts multiple neighbors using the --neighbor parameter. It's unclear how the GUI can be used to configure multiple neighbors. Current version only accepts a single neighbor

**To Reproduce**
1. Start GUI
2. Enter 2 or more neighborhood descriptors
3. Fill in the other fields

**Expected behavior**

**Screenshots**
The screenshot shows the error while 2 neighbors were entered, seperated by a comma.
![two neighbors error](https://user-images.githubusercontent.com/23551316/54036970-3e381d00-41bd-11e9-8a46-d4f06469baf8.png)

**Log files**
Include any relevant logging information. (e.g. /tmp/SubstratumNode.log on Ubuntu)

**Device Details (please complete the following information):**
 - Device Type: Desktop
 - OS name and version OSX 10.13.6

**Additional context**
Tried multiple options to enter multiple neighbors, using comma seperated, spaces, hyphens.. neither works.

**Comment by SUB-BJ** [comment]
This is related to feature request SC-783: Add multiple neighbors by descriptor through GUI.

This is not MVP since our Gossip protocol is sufficient to dynamically build neighborhoods once the initial neighbor is added. This does mean that MVP will rely on social connections a bit more than we'd like and the ability for Node users to choose a sufficiently good first neighbor. We acknowledge this is very much a happy path scenario but it's good enough for MVP and only limits knowledge of the entire network between segments.
